[tool.poetry]
name = "lab-1"
description = ""
authors = []
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.10"
openai = "^0.28.0"
tiktoken = "^0.5.1"
fire = "^0.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
